### ISSUE TITLE
Can you share the metadata of YFCC100M?

### ISSUE THREAD

**Issue by Chen-Song** [akisatok/yfcc100m-download#1]
Hi, akisatok
It may be because of the network of mine, the metadata of the downloaded YFCC100M is often wrong. Could you share the following metadata with me.

'yfcc100m_autotags.csv'
'yfcc100m_exif.csv'
'yfcc100m_places.csv'
'yfcc100m_dataset.csv'

Thanks

**Comment by akisatok** [comment]
Dear Chen-Song,

I do not have those metadata now, since this code was developed during my stay in Cambridge and almost all the data related to this project have to leave as-is. Also, I am afraid that it might be difficult to share on github, since size of those metadata is too huge to share.

Sorry for the inconvenience.
